permalink: /:categories/:title/
title: FUNBIT
email: post@funbit.no
description: this means to ignore newlines until "baseurl:" Det er sikkert lett å skrive noe her som noe eksempel for denne siden.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AlexFUNBIT
github_username:  AlexFUNBIT

page.lang: no

# Build settings
markdown: kramdown
theme: funbit

plugins:
  - jekyll-feed
  - jekyll-sitemap

google_analytics: UA-NNNNNNNN-N

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
